version: '3'

services:
  clamav-server:
    container_name: clamav-server
    image: mkodockx/docker-clamav
    ports:
      - "3310:3310"
  clamav-rest:
    build: . # run Dockerfile
    container_name: clamav-rest
    depends_on:
      - clamav-server
    environment:
      - CLAMD_HOST=clamav-server
    links:
      - clamav-server:clamav-server
    ports:
      - "8080:8080"
